name: Geely Design Web
markdown: kramdown
highlighter: rouge
include:
  - '_pages'
exclude:
  - Gemfile
  - Gemfile.lock

baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title/
siteurl: https://geelydesign.github.io/geelydesignweb/
imageurl: https://geelydesign.github.io/geelydesignweb/assets/img/

gems:
  - jekyll-feed

title: Geely Design Web
email: your-email@domain.com
description: 
  en: >
    Geely Design is a multi-cultural global organization under the leadership of Peter Horbury with four 
    well-equipped studios in Shanghai, Gothenburg, Barcelona and Los Angeles with some 450 people in total. 
    These design centers, with top class design teams and the latest tools in design development, are 
    responsible for the creation of a unique design language for each of Geely's brands.
  cn: >
    吉利设计（Geely Design）是在彼得·霍布里（Peter Horbury）先生领导下的一个多元化的国际性机构，在上海、哥德堡、
    巴塞罗那和加利福尼亚分别设有功能完备的设计中心，员工总数约为450人。四大设计中心拥有顶级的设计团队和先进的设计研发设备，
    负责为吉利的各个品牌车系精心打造独一无二的设计语言。

header:
  image: bg/bg_04.jpg
  logo: bg/gd-logo-white.svg
  menu:
    en: English
    cn: 中文

prefooter:
  image: bg/bg_02.jpg

footer:
  title:
    en: Keep in touch
    cn: 保持联系

  copy: 2017 Geely Design

  name:
    text:
      en: Geely Group
      cn: Geely Group
    href: http://www.geelyholding.com

  social: 
    facebook: ''
    linkedin: https://www.linkedin.com/company/geely-design-global
    wechat: http://mp.weixin.qq.com/s/d56hYo3uYwQxJ1N5CGSz-A

  btn:
    contact:
      text:
        en: say hi
        cn: 和我们打个招呼吧
      href: info@geelydesign.com
    join:
      text:
        en: join us
        cn: 加入我们
      href: https://www.linkedin.com/company/geely-design-global

  box1:
    title:
      en: Geely Design China
      cn: Geely Design China
    company:
      en: Ningbo Geely Automotive Research & Development Co. Ltd Shanghai Sub-Company
      cn: Ningbo Geely Automotive Research & Development Co. Ltd Shanghai Sub-Company
    address:
      street:
        en: 388 Guo Zhan Road
        cn: 388 Guo Zhan Road
      zip:
        en: Pu Dong District, Shanghai
        cn: Pu Dong District, Shanghai
      country:
        en: P.R China 200126
        cn: P.R China 200126
  box2:
    title:
      en: Geely Design Europe
      cn: Geely Design Europe
    address:
      street:
        en: Valdemar Noréns Gata 3
        cn: Valdemar Noréns Gata 3
      zip:
        en: SE - 417 55 Göteborg
        cn: SE - 417 55 Göteborg
      country:
        en: Sweden
        cn: Sweden
  box3:
    title:
      en: Geely Design Barcelona
      cn: Geely Design Barcelona
    address:
      street:
        en: Calle Diputacio 246
        cn: Calle Diputacio 246
      zip:
        en: 08007 Barcelona
        cn: 08007 Barcelona
      country:
        en: Spain
        cn: Spain
  box4:
    title:
      en: Geely Design California
      cn: Geely Design California
    address:
      street:
        en: 700 Via Alondra
        cn: 700 Via Alondra
      zip:
        en: Camarillo, California 93012
        cn: Camarillo, California 93012
      country:
        en: United States
        cn: United States
