name: Geely Design Web
markdown: kramdown
highlighter: rouge
include:
  - '_pages'
exclude:
  - Gemfile
  - Gemfile.lock

baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title/
siteurl: https://hiqgoteborg.github.io/geelydesign.github.io/
imageurl: https://hiqgoteborg.github.io/geelydesign.github.io/assets/img/

gems:
  - jekyll-feed

title: Geely Design Web
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

facebook: https://www.facebook.com/ThemeInTheBox/
twitter: https://twitter.com/ThemeintheBox

header:
  image: landing_image.jpg
  menu:
    en: English
    cn: 中文

prefooter:
  image: bg_02.jpg

footer:
  title:
    en: Keep in touch
    cn: Kontakta oss

  copy: 2017 Geely Design

  name: Geely Group

  social: SOCIAL MEDIA

  btn:
    contact:
      text:
        en: say hi
        cn: säg hej
      href: info@geelydesign.com
    join:
      text:
        en: join us
        cn: gå med
      href: ''

  box1:
    title:
      en: Geely Design China
      cn: Geely Design China
    company:
      en: Ningbo Geely Automotive Research & Development Co. Ltd Shanghai Sub-Company
      cn: Ningbo Geely Automotive Research & Development Co. Ltd Shanghai Sub-Company
    address:
      street:
        en: 388 Guo Zhan Road
        cn: 388 Guo Zhan Road
      zip:
        en: Pu Dong District, Shanghai
        cn: Pu Dong District, Shanghai
      country:
        en: P.R China 200126
        cn: P.R China 200126
  box2:
    title:
      en: Geely Design Europe
      cn: Geely Design Europe
    address:
      street:
        en: Valdemar Noréns Gata 3
        cn: Valdemar Noréns Gata 3
      zip:
        en: SE - 417 55 Göteborg
        cn: SE - 417 55 Göteborg
      country:
        en: Sweden
        cn: Sweden
  box3:
    title:
      en: Geely Design Barcelona
      cn: Geely Design Barcelona
    address:
      street:
        en: Diputacio 246
        cn: Diputacio 246
      zip:
        en: 8007 Barcelona
        cn: 8007 Barcelona
      country:
        en: Spain
        cn: Spain
  box4:
    title:
      en: Geely Design Los Angeles
      cn: Geely Design Los Angeles
    address:
      street:
        en: 700 Via Alondra
        cn: 700 Via Alondra
      zip:
        en: 93012 Los Angeles CA
        cn: 93012 Los Angeles CA
      country:
        en: United States
        cn: United States